import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const corsHeaders={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"content-type, idempotency-key","Access-Control-Allow-Methods":"POST, OPTIONS"},MAX_BYTES=512000;
const customerTypes=new Set(["school","dealer","individual","other"]),contacts=new Set(["call","whatsapp","email"]),existingCustomers=new Set(["Yes","No","Not sure"]),mobile=/^[6-9]\d{9}$/,email=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...corsHeaders,"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}});
const object=(value:unknown):value is Record<string,unknown>=>Boolean(value)&&typeof value==="object"&&!Array.isArray(value);
const keys=(value:Record<string,unknown>,allowed:string[])=>Object.keys(value).every(key=>allowed.includes(key));
const text=(value:unknown,max:number,required=false)=>typeof value==="string"&&value.length<=max&&(!required||value.trim().length>0);
const optionalText=(value:unknown,max:number)=>value===null||value===undefined||text(value,max);
const uuid=(value:unknown)=>typeof value==="string"&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value);
function validPayload(payload:unknown,key:string|null){
  if(!object(payload)||!keys(payload,["customer","notes","items","idempotencyKey"])||!uuid(payload.idempotencyKey)||key!==payload.idempotencyKey)return false;
  const customer=payload.customer,items=payload.items;
  if(!object(customer)||!keys(customer,["customerType","contactName","organisationName","mobile","whatsapp","email","preferredContact","location","existingCambridgeCustomer"])||!object(customer.location)||!keys(customer.location,["city","district","state","pincode"])||!Array.isArray(items)||items.length<1||items.length>1000)return false;
  if(!text(customer.customerType,20,true)||!customerTypes.has(customer.customerType)||!text(customer.contactName,80,true)||customer.contactName.trim().length<2||!text(customer.mobile,10,true)||!mobile.test(customer.mobile)||!optionalText(customer.organisationName,120)||!optionalText(customer.whatsapp,10)||!optionalText(customer.email,120)||!text(customer.preferredContact,20,true)||!contacts.has(customer.preferredContact)||!text(customer.existingCambridgeCustomer,20,true)||!existingCustomers.has(customer.existingCambridgeCustomer)||!text(customer.location.city,80,true)||customer.location.city.trim().length<2||!optionalText(customer.location.district,80)||!optionalText(customer.location.state,80)||!optionalText(customer.location.pincode,6)||!text(payload.notes??"",500))return false;
  if(["school","dealer","other"].includes(customer.customerType)&&(!text(customer.organisationName,120,true)||customer.organisationName.trim().length<2))return false;
  if(customer.whatsapp!==null&&customer.whatsapp!==undefined&&(!text(customer.whatsapp,10,true)||!mobile.test(customer.whatsapp)))return false;
  if(customer.email!==null&&customer.email!==undefined&&(!text(customer.email,120,true)||!email.test(customer.email)))return false;
  if(customer.preferredContact==="email"&&(typeof customer.email!=="string"||!email.test(customer.email)))return false;
  if(customer.preferredContact==="whatsapp"&&(typeof customer.whatsapp!=="string"||!mobile.test(customer.whatsapp)))return false;
  if(customer.location.pincode!==null&&customer.location.pincode!==undefined&&(!text(customer.location.pincode,6,true)||!/^\d{6}$/.test(customer.location.pincode)))return false;
  return items.every(item=>{if(!object(item)||!text(item.type,20,true)||!Number.isSafeInteger(item.quantity)||item.quantity<1||item.quantity>10000)return false;if(item.type==="book")return keys(item,["type","publicationId","quantity"])&&uuid(item.publicationId);if(item.type==="custom-kit")return keys(item,["type","level","kitName","publicationIds","quantity"])&&text(item.level,30,true)&&(item.kitName===null||text(item.kitName,80))&&Array.isArray(item.publicationIds)&&item.publicationIds.length>0&&item.publicationIds.length<=1000&&item.publicationIds.every(uuid);if(item.type==="standard-kit")return keys(item,["type","level","kitName","publicationIds","quantity"])&&text(item.level,30,true)&&item.kitName===null&&Array.isArray(item.publicationIds)&&item.publicationIds.length>0&&item.publicationIds.length<=1000&&item.publicationIds.every(uuid);return false});
}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:corsHeaders});if(req.method!=="POST")return json({ok:false,error:"Method not allowed"},405);if(!(req.headers.get("content-type")||"").toLowerCase().includes("application/json"))return json({ok:false,error:"Content-Type must be application/json"},415);const length=Number(req.headers.get("content-length"));if(Number.isFinite(length)&&length>MAX_BYTES)return json({ok:false,error:"Request payload is too large"},413);const raw=await req.text();if(new TextEncoder().encode(raw).byteLength>MAX_BYTES)return json({ok:false,error:"Request payload is too large"},413);let payload:unknown;try{payload=JSON.parse(raw)}catch{return json({ok:false,error:"Invalid JSON"},400)}const key=req.headers.get("idempotency-key");if(!validPayload(payload,key))return json({ok:false,error:"Please check the request details and try again."},400);const url=Deno.env.get("SUPABASE_URL"),serviceRoleKey=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!serviceRoleKey){console.error("Submission service configuration unavailable");return json({ok:false,error:"Submission service is unavailable"},503)}const supabase=createClient(url,serviceRoleKey,{auth:{persistSession:false,autoRefreshToken:false}}),{data,error}=await supabase.rpc("submit_catalogue_request",{payload});if(error){console.error("submit_catalogue_request failed",error.code);const validation=["P0001","23514","22P02"].includes(error.code);return json({ok:false,error:validation?"Please check the request details and try again.":"We could not submit your request. Please try again."},validation?400:500)}if(!data||data.ok!==true||!data.reference)return json({ok:false,error:"We could not confirm your request. Please try again."},500);return json({ok:true,reference:data.reference},data.replayed?200:201)});
