import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
const corsHeaders={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"content-type, idempotency-key","Access-Control-Allow-Methods":"POST, OPTIONS"},MAX_BYTES=512000;
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...corsHeaders,"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}});
const object=(value:unknown):value is Record<string,unknown>=>Boolean(value)&&typeof value==="object"&&!Array.isArray(value);
const keys=(value:Record<string,unknown>,allowed:string[])=>Object.keys(value).every(key=>allowed.includes(key));
const text=(value:unknown,max:number,required=false)=>typeof value==="string"&&(required?value.trim().length>0:true)&&value.length<=max;
const uuid=(value:unknown)=>typeof value==="string"&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value);
function validPayload(payload:unknown,key:string|null){if(!object(payload)||!keys(payload,["customer","notes","items","idempotencyKey"])||!uuid(payload.idempotencyKey)||key!==payload.idempotencyKey)return false;const customer=payload.customer,items=payload.items;if(!object(customer)||!keys(customer,["customerType","contactName","organisationName","mobile","whatsapp","email","preferredContact","location","existingCambridgeCustomer","notes"])||!object(customer.location)||!keys(customer.location,["city","district","state","pincode"])||!Array.isArray(items)||items.length<1||items.length>1000)return false;if(!text(customer.contactName,150,true)||!text(customer.mobile,30,true)||!text(customer.location.city,200,true)||!text(payload.notes??"",2000)||!text(customer.organisationName??"",200)||!text(customer.email??"",254)||!text(customer.whatsapp??"",30)||!text(customer.location.district??"",200)||!text(customer.location.state??"",200)||!text(customer.location.pincode??"",20))return false;return items.every(item=>{if(!object(item)||!text(item.type,20,true)||!Number.isSafeInteger(item.quantity)||item.quantity<1||item.quantity>10000)return false;if(item.type==="book")return keys(item,["type","publicationId","quantity"])&&uuid(item.publicationId);if(item.type==="custom-kit"||item.type==="standard-kit")return keys(item,["type","level","kitName","publicationIds","quantity"])&&text(item.level,30,true)&&(!item.kitName||text(item.kitName,80))&&Array.isArray(item.publicationIds)&&item.publicationIds.length>0&&item.publicationIds.length<=1000&&item.publicationIds.every(uuid);return false})}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:corsHeaders});if(req.method!=="POST")return json({ok:false,error:"Method not allowed"},405);if(!(req.headers.get("content-type")||"").toLowerCase().includes("application/json"))return json({ok:false,error:"Content-Type must be application/json"},415);const length=Number(req.headers.get("content-length"));if(Number.isFinite(length)&&length>MAX_BYTES)return json({ok:false,error:"Request payload is too large"},413);const raw=await req.text();if(new TextEncoder().encode(raw).byteLength>MAX_BYTES)return json({ok:false,error:"Request payload is too large"},413);let payload:unknown;try{payload=JSON.parse(raw)}catch{return json({ok:false,error:"Invalid JSON"},400)}const key=req.headers.get("idempotency-key");if(!validPayload(payload,key))return json({ok:false,error:"Please check the request details and try again."},400);const url=Deno.env.get("SUPABASE_URL"),serviceRoleKey=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!serviceRoleKey){console.error("Submission service configuration unavailable");return json({ok:false,error:"Submission service is unavailable"},503)}const supabase=createClient(url,serviceRoleKey,{auth:{persistSession:false,autoRefreshToken:false}}),{data,error}=await supabase.rpc("submit_catalogue_request",{payload});if(error){console.error("submit_catalogue_request failed",error.code);const validation=["P0001","23514","22P02"].includes(error.code);return json({ok:false,error:validation?"Please check the request details and try again.":"We could not submit your request. Please try again."},validation?400:500)}if(!data||data.ok!==true||!data.reference)return json({ok:false,error:"We could not confirm your request. Please try again."},500);return json({ok:true,reference:data.reference},data.replayed?200:201)});
